/**
 * `abg shell-init <shell>` — emit a shell snippet that wraps `codex` and
 * `claude` so the user can opt into bridge attachment with a `--abg`
 * sentinel flag.
 *
 *   codex --abg              → routes through `abg codex` (bridge attach)
 *   codex                    → native binary (default; bridge is OFF unless asked)
 *   codex --abg resume --last → bridge + pass through resume
 *
 * Installed via:
 *
 *   eval "$(abg shell-init bash)"        # interactive (one shell)
 *   abg shell-init bash >> ~/.bashrc     # persist for new shells
 *
 * Supported shells: bash, zsh, fish, sh (POSIX subset that bash also accepts).
 *
 * Design notes:
 * - The wrapper functions are named `codex` and `claude`, which shadow the
 *   real binaries. They ALWAYS fall back to `command codex` /
 *   `command claude` when `--abg` is absent — opt-in only, no implicit
 *   bridging based on daemon state.
 * - The sentinel is stripped from the args before forwarding so the inner
 *   command never sees `--abg`.
 */

export type SupportedShell = "bash" | "zsh" | "fish" | "sh";

const SHELL_ALIASES: Record<string, SupportedShell> = {
  bash: "bash",
  zsh: "zsh",
  fish: "fish",
  sh: "sh",
};

export function detectShell(envShell: string | undefined): SupportedShell | null {
  if (!envShell) return null;
  const base = envShell.split("/").pop();
  if (!base) return null;
  return SHELL_ALIASES[base] ?? null;
}

export function renderShellSnippet(shell: SupportedShell): string {
  switch (shell) {
    case "bash":
    case "zsh":
    case "sh":
      return renderPosixSnippet();
    case "fish":
      return renderFishSnippet();
  }
}

function renderPosixSnippet(): string {
  return `# >>> agentbridge shell-init >>>
# Generated by \`abg shell-init\`. Wraps \`codex\` and \`claude\` so you can
# opt into bridge attachment with a \`--abg\` sentinel flag. Default is
# OFF — the wrapper always runs the native binary unless \`--abg\` is
# present.
#
#   codex --abg                  → route through \`abg codex\` (bridge on)
#   codex                        → native codex, no bridge
#   codex --abg resume --last    → bridge + pass through subcommand
#
# Same flags work for \`claude\`. Remove this block to uninstall.

__agb_route() {
  # __agb_route <native-binary> <abg-subcommand> [args...]
  local native="$1"; shift
  local subcmd="$1"; shift
  local bridge=0
  local -a cleaned=()
  local arg
  for arg in "$@"; do
    if [ "$arg" = "--abg" ]; then
      bridge=1
    else
      cleaned+=("$arg")
    fi
  done
  if [ "$bridge" = "1" ]; then
    command abg "$subcmd" "\${cleaned[@]}"
  else
    command "$native" "\${cleaned[@]}"
  fi
}

codex()  { __agb_route codex  codex  "$@"; }
claude() { __agb_route claude claude "$@"; }
# <<< agentbridge shell-init <<<
`;
}

function renderFishSnippet(): string {
  return `# >>> agentbridge shell-init >>>
# Generated by \`abg shell-init\`. Wraps \`codex\` and \`claude\` so you can
# opt into bridge attachment with a \`--abg\` sentinel flag. Default is
# OFF — the wrapper always runs the native binary unless \`--abg\` is
# present.
#
#   codex --abg                  → route through \`abg codex\` (bridge on)
#   codex                        → native codex, no bridge
#   codex --abg resume --last    → bridge + pass through subcommand
#
# Same flags work for \`claude\`. Remove this block to uninstall.

function __agb_route
    set -l native $argv[1]
    set -l subcmd $argv[2]
    set -e argv[1..2]
    set -l bridge 0
    set -l cleaned
    for arg in $argv
        if test "$arg" = "--abg"
            set bridge 1
        else
            set cleaned $cleaned $arg
        end
    end
    if test "$bridge" = "1"
        command abg $subcmd $cleaned
    else
        command $native $cleaned
    end
end

function codex
    __agb_route codex codex $argv
end

function claude
    __agb_route claude claude $argv
end
# <<< agentbridge shell-init <<<
`;
}

export interface ShellInitOptions {
  shellArg?: string;
  envShell?: string;
}

export function resolveShell(opts: ShellInitOptions): SupportedShell {
  if (opts.shellArg) {
    const normalized = opts.shellArg.toLowerCase();
    const matched = SHELL_ALIASES[normalized];
    if (!matched) {
      throw new Error(
        `Unsupported shell: ${opts.shellArg!}. Supported: bash, zsh, fish, sh.`,
      );
    }
    return matched;
  }
  const detected = detectShell(opts.envShell);
  if (detected) return detected;
  throw new Error(
    "Could not detect shell from $SHELL. Pass an explicit arg: `abg shell-init bash|zsh|fish|sh`.",
  );
}

export async function runShellInit(args: string[]): Promise<void> {
  if (args.includes("--help") || args.includes("-h")) {
    process.stdout.write(`Usage:
  abg shell-init [bash|zsh|fish|sh]   # emit shell snippet on stdout
  eval "$(abg shell-init)"            # install in current shell
  abg shell-init bash >> ~/.bashrc    # persist for new shells

Installs wrapper functions for \`codex\` and \`claude\`:
  --abg     route via bridge (opt-in; default is native)
  (none)    native binary, no bridge
`);
    return;
  }
  const shell = resolveShell({
    shellArg: args[0],
    envShell: process.env.SHELL,
  });
  process.stdout.write(renderShellSnippet(shell));
}
